-- Nerd-font glyphs as escapes, so the codepoints stay visible in the source
-- and survive tools that drop private-use characters.
return {
    error = "\u{F0159}",
    warning = "\u{F0026}",
    info = "\u{F02FC}",
    hint = "\u{F0335}",
    breakpoint = "\u{F111}",
    breakpoint_condition = "\u{F059}",
    breakpoint_rejected = "\u{F05E}",
    stopped = "\u{F0A4}",
    open = "\u{EB7F}",
    fold_open = "\u{F078}",
    fold_closed = "\u{F054}",
    vsplit = "\u{EB56}",
    hsplit = "\u{EB57}",
    new_file = "\u{F501}",
    new_folder = "\u{EEC7}",
    delete = "\u{F52F}",
    rename = "\u{F458}",
    copy = "\u{F4BB}",
    cut = "\u{F0C4}",
    paste = "\u{F429}",
    path = "\u{F0D20}",
    relative_path = "\u{F506}",
    pin = "\u{F0403}",
    clipboard = "\u{F0EA}",
    close_all = "\u{EBBA}",
    close_left = "\u{EAB5}",
    close_right = "\u{EAB6}",
    browser = "\u{F0AC}",
    definition = "\u{F05B}",
    code_action = "\u{F0EB}",
    format = "\u{F036}",
    implementation = "\u{F0E8}",
    references = "\u{F0C1}",
    signature = "\u{F129}",
    diagnostics = "\u{F0F1}",
    list = "\u{F03A}",
    select_all = "\u{F046}",
    copy_all = "\u{F0C5}",
    inspect = "\u{F002}",
    config = "\u{F013}",
}
